import type { ExtractedData } from '@/types'

export function generateMarkdown(data: ExtractedData): string {
  const lines: string[] = [
    `# ${data.courseName || 'Untitled Course'}`,
    '',
    `**Instructor:** ${data.instructor || 'Unknown'}`,
    `**Semester:** ${data.semester || 'Unknown'}`,
    '',
    '## Important Dates',
    '',
    '| Date | Type | Title | Weight |',
    '|------|------|-------|--------|',
  ]

  const events = data.events || []
  const sortedEvents = [...events].sort((a, b) => {
    const dateA = new Date(a.dueDate).getTime()
    const dateB = new Date(b.dueDate).getTime()
    if (isNaN(dateA)) return 1
    if (isNaN(dateB)) return -1
    return dateA - dateB
  })

  for (const event of sortedEvents) {
    lines.push(
      `| ${event.dueDate || 'TBD'} | ${event.type || 'other'} | ${event.title || 'Untitled'} | ${event.weight || '-'} |`
    )
  }

  lines.push('', '---', '', '## Detailed Breakdown', '')

  for (const event of sortedEvents) {
    lines.push(`### ${event.title || 'Untitled'}`)
    lines.push(`- **Type:** ${event.type || 'other'}`)
    lines.push(`- **Due:** ${event.dueDate || 'TBD'}`)
    if (event.weight) lines.push(`- **Weight:** ${event.weight}`)
    if (event.description) lines.push(`- **Description:** ${event.description}`)
    lines.push('')
  }

  lines.push('---', '', '*Generated by Syllabus Parser*')

  return lines.join('\n')
}
