export const config = {
  runtime: 'nodejs',
  maxDuration: 60
}

const EXTRACTION_PROMPT = `You are a syllabus parser. Extract all important dates, deadlines, and events from the provided syllabus text.

Return a JSON object with this exact structure:
{
  "courseName": "Course title",
  "instructor": "Professor name",
  "semester": "e.g., Spring 2026",
  "events": [
    {
      "type": "assignment|midterm|final|quiz|project|other",
      "title": "Event name",
      "dueDate": "YYYY-MM-DD format",
      "description": "Brief description (optional)",
      "weight": "Percentage of grade (optional)"
    }
  ]
}

Guidelines:
- Extract ALL dates mentioned: assignments, exams, quizzes, projects, presentations
- Convert relative dates (e.g., "Week 3") to actual dates if semester start is known
- If exact date unknown, estimate based on context
- Include weight/percentage if mentioned
- Type should be: assignment, midterm, final, quiz, project, or other
- Always use YYYY-MM-DD format for dates
- If year is not specified, assume 2025 academic year
- Return ONLY valid JSON, no markdown or extra text`

function generateMarkdown(data: any): string {
  const lines: string[] = [
    `# ${data.courseName || 'Untitled Course'}`,
    '',
    `**Instructor:** ${data.instructor || 'Unknown'}`,
    `**Semester:** ${data.semester || 'Unknown'}`,
    '',
    '## Important Dates',
    '',
    '| Date | Type | Title | Weight |',
    '|------|------|-------|--------|'
  ]

  const events = data.events || []
  const sortedEvents = [...events].sort((a: any, b: any) => {
    const dateA = new Date(a.dueDate).getTime()
    const dateB = new Date(b.dueDate).getTime()
    if (isNaN(dateA)) return 1
    if (isNaN(dateB)) return -1
    return dateA - dateB
  })

  for (const event of sortedEvents) {
    lines.push(
      `| ${event.dueDate || 'TBD'} | ${event.type || 'other'} | ${event.title || 'Untitled'} | ${event.weight || '-'} |`
    )
  }

  lines.push('', '---', '', '## Detailed Breakdown', '')

  for (const event of sortedEvents) {
    lines.push(`### ${event.title || 'Untitled'}`)
    lines.push(`- **Type:** ${event.type || 'other'}`)
    lines.push(`- **Due:** ${event.dueDate || 'TBD'}`)
    if (event.weight) lines.push(`- **Weight:** ${event.weight}`)
    if (event.description) lines.push(`- **Description:** ${event.description}`)
    lines.push('')
  }

  lines.push('---', '', '*Generated by Syllabus Parser*')

  return lines.join('\n')
}

interface ExtractRequest {
  text: string
  model: string
  apiKey?: string
}

interface OpenRouterResponse {
  choices: Array<{
    message: {
      content: string
      reasoning?: string
    }
  }>
  model: string
  usage?: {
    prompt_tokens: number
    completion_tokens: number
    total_tokens: number
  }
}

export default async function handler(req: Request) {
  if (req.method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, { status: 405 })
  }

  try {
    const { text, model, apiKey: clientKey }: ExtractRequest = await req.json() as ExtractRequest

    // Use server-side key if available, otherwise use client-provided key
    const apiKey = process.env.OPENROUTER_API_KEY || clientKey

    if (!text || !model) {
      return Response.json({ success: false, error: 'Missing required fields' })
    }

    if (!apiKey) {
      return Response.json({ success: false, error: 'No API key configured' })
    }

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://syllabus-parser.vercel.app',
        'X-Title': 'Syllabus Parser'
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: EXTRACTION_PROMPT },
          { role: 'user', content: `Extract dates and events from this syllabus:\n\n${text}` }
        ],
        temperature: 0.1
      })
    })

    if (!response.ok) {
      const error = await response.text()
      throw new Error(`OpenRouter API error: ${response.status} - ${error}`)
    }

    const data = await response.json() as OpenRouterResponse
    const choice = data.choices[0]
    if (!choice) {
      throw new Error('No response from AI model')
    }
    const content = choice.message.content

    // Parse JSON response
    let extracted
    try {
      let cleanContent = content.trim()
      if (cleanContent.startsWith('```json')) cleanContent = cleanContent.slice(7)
      if (cleanContent.startsWith('```')) cleanContent = cleanContent.slice(3)
      if (cleanContent.endsWith('```')) cleanContent = cleanContent.slice(0, -3)
      extracted = JSON.parse(cleanContent.trim())
    } catch {
      return Response.json({
        success: false,
        error: 'Failed to parse AI response as JSON',
        rawResponse: content,
        model: data.model,
        usage: data.usage
      })
    }

    const markdown = generateMarkdown(extracted)

    return Response.json({
      success: true,
      extracted,
      markdown,
      model: data.model,
      usage: data.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
      reasoning: choice.message.reasoning
    })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Extraction failed'
    return Response.json({ success: false, error: message })
  }
}
